### ISSUE TITLE
Create a full OS image with a working SkyWire instance on it.

### ISSUE THREAD

**Issue by stdevPavelmc** [skycoin/skybian#1]
Create a full OS image with a working SkyWire instance on it for the Orange Pi Prime SBC. The OS images must be integrated with SkyWire to solve the issues and short comings of the actual Skyminer images.

This are the main features needed:

- [x] Armbian base OS without the forced user creation at first boot
- [x] Golang aarm64 installed on a version specified in a file
- [x] Skywire cloned from master repo
- [x] Travis integration to push the final images on master branch
- [x] Generation of a single image to be used as default
- [x] Versioning schema to trigger master branch on new tag

**Comment by stdevHan** [comment]
@stdevPavelmc  test

**Comment by stdevHan** [comment]
test

**Comment by stdevHan** [comment]
test

**Comment by stdevHan** [comment]
test

**Comment by stdevPavelmc** [comment]
At this point the Images are usable, working on test of the images to validate the usability, and improving the Github Release via Travis.

**Comment by olemis** [comment]
fixed by #9
