### ISSUE TITLE
Nodes can't find uptime tracker (404)

### ISSUE THREAD

**Issue by tanevanwifferen** [skycoin/skybian#109]
**Describe the bug**
All our (hyper)visor nodes can't find the uptime tracker. The status indicator is orange, and all details are are green except for the uptime tracker indicator.

**Environment information:**

- OS: Skybian
- Platform: official skyminer 0.4.1

**Steps to Reproduce**

don't know?

**Actual behavior**
No idea really what is happening, where can I find the URLs?

**Expected behavior**
The node should find the uptime tracker

**Additional context**
Nothing really, we're running a fresh install, it has worked when the nodes were just installed.

**Possible implementation**
Should be working already?

**Comment by jdknives** [comment]
Deployment issue most likely. Not a Skybian issue.
