### ISSUE TITLE
SSH and Login do not work

### ISSUE THREAD

**Issue by authrequest** [skycoin/skybian#110]
I currently have a Raspberry Pi 4 - 4GB that I am trying to get online using the prebuilt Skybian 64bit for the Pi. I have looked through various locations in the documentation and I am unable to SSH or login locally into the Pi. 

I have tried pi/raspberry and root/skybian but none seem to work.
Is this still being actively being developed?

Is there a way to get this setup ? I have 8 Pis that I would love to setup as nodes

**Comment by jdknives** [comment]
@authrequest thanks for making this ticket. Please provide us with the following information:

- commands you ran
- error logs you got 
- image you used and version you used (Skyimager GUI and image)

**Comment by authrequest** [comment]
@jdknives I used the latest image v0.3.0. I simply extracted the .img file and used balenaetcher to write it to my USB drive (I have USB boot enabled) and when I started it up and tried to SSH into the RPi, I would get an error that the login was incorrect. I tried locally as well but I was unable to get in.
Logins Tried:
Username: pi
Password: raspberry

Username: root
Password: skybian

I have been trying to get it up and running for the last few hours but have been unsuccessful. I tried even running 64bit Raspberry Pi OS but still getting an error.

**Comment by Asgaror** [comment]
Have you processed the base image using Skyimager before flashing it via balenaetcher? The default credentials user `root` and password `skybian` are valid. Here's the related user guide with details on these credentails: 
- https://github.com/skycoin/skywire/wiki/Skyimager-User-Guide
