### ISSUE TITLE
fyne-cross darwin image

### ISSUE THREAD

**Issue by mrpalide** [skycoin/skybian#121]
**Description**
After upgrade fyne to version 2.1.1, fyne-cross for cross-building has new limitation for darwin images. Base on [this](https://github.com/fyne-io/fyne-cross#build-the-docker-image-for-osxdarwinapple-cross-compiling) no darwin image exist fyne-cross dockerhub and we should create it locally. So if we want use it in CI process, we should create the image once and push it on our private repository, then pull/use it from our dockerhub in CI process each time.

**Comment by alexadhy** [comment]
can we close this @mrpalide
