### ISSUE TITLE
Hypervisor Systemd service is not starting

### ISSUE THREAD

**Issue by jdknives** [skycoin/skybian#14]
**Describe the bug**
The hypervisor service is not starting. (Logs attached).
[hyp.txt](https://github.com/SkycoinProject/skybian/files/4440959/hyp.txt)
**Environment information:**

- OS: e.g.Skybian

**Hints:**
The hypervisor config is not existent (similar issues have been reported with visors) in `/etc/

`

**Comment by evanlinjin** [comment]
@jdknives Damn, but visor is okay?

**Comment by jdknives** [comment]
Not sure. @asxtree will need to get more info.

**Comment by evanlinjin** [comment]
@jdknives I got the OrangePi but not an SD card reader so can't write image. I've ordered one online and should arrive tomorrow or the day after,

**Comment by jdknives** [comment]
Copy. Maybe we can still investigate the issue with @Asgaror and @asxtree helping.

**Comment by jdknives** [comment]
Seems fixed by the recent changes.
