### ISSUE TITLE
skyimager-gui: cannot use existing Local Base Image

### ISSUE THREAD

**Issue by some4** [skycoin/skybian#17]
Under the "Base Image:" section; option "From local filesystem."; it asks for the "path to .img file."

If I provide the path, e.g. `C:\Users\some4\skyimager\base`, I get: 
"_Error: Invalid Base Image Path: file needs to have .img extension_"

In ..\skyimager\base there _**is**_ an image file, but the extension is ".3"

**Environment information:**

- Windows10 Pro, version 1809
- macOS High Sierra, 10.13.6; Darwin 17.7.0

**Steps to Reproduce**

- Download a Base Image (release) using the "From remote server" option
- Build a hypervisor or 1 visor image
- When done, press the "Previous" button and try use the "From local filesystem." option

**Additional context**
I manually renamed the file to end with .img and it gave the same error.

**Possible implementation**

- ".img" in place of the patch version for the extension

**Comment by evanlinjin** [comment]
@some4
1. You need to provide the full path of the `.img` file. For example `C:\Users\some4\skyimager\base\Skybian-v0.1.0-alpha.3.img`.
2. Windows file explorer hides the file extension for some files. Hence, the `.img` would not be shown, but `skyimager` requires you include this.

**Comment by some4** [comment]
> @some4
> 
> 1. You need to provide the full path of the `.img` file. For example `C:\Users\some4\skyimager\base\Skybian-v0.1.0-alpha.3.img`.
> 2. Windows file explorer hides the file extension for some files. Hence, the `.img` would not be shown, but `skyimager` requires you include this.

I provided the path you suggested and now I get:
"Error: cannot access Base Image: CreateFile C:\Users\some4\skyimager\base\Skybian-v0.1.0-alpha.3.img"

"CreateFile" looks suspicious.

edit: add @evanlinjin , *Windows10 Pro, version 1809

**Comment by some4** [comment]
@evanlinjin 

I didn't mention you for the comment above (apologies, still getting used to this)
