### ISSUE TITLE
skyimager-gui: multiple error types during no network condition

### ISSUE THREAD

**Issue by some4** [skycoin/skybian#18]
I've produced two errors:

1. Get https:api.github.com/repos/SkycoinProject/skybian/releases: dial tcp: lookup api.github.com: no such host
2. context deadline exceeded

When _we_ read these we have an idea of the problem and know where to look. 

But if I didn't know any better: the first one implies that the host doesn't exist; the second one is a fancy timeout.

**Environment information:**

- Windows10 Pro, version 1809
- macOS High Sierra, 10.13.6; Darwin 17.7.0

**Steps to Reproduce**

- For error#1: **First** disable or unplug network adapter _then_ run `skyimager-gui`
- For error#2: (with a working network connection) run `skyimager-gui`; press "Next"; _then_ disable or unplug network adapter; press "Previous"; press "Next"

**Possible implementation**
Maybe suggest to the user that they should first check their network connection (or test it for them)?

The direct link to the releases is a huge feature, well done!

**Comment by evanlinjin** [comment]
@some4 Thank you for your ticket.

However, this is not a bug, but a suggestion on how to improve the user experience. In the future, such tickets should use the tag `enhancement` and not `bug`.

**Comment by some4** [comment]
Noted, thank you. Github only gave me the option for Bug or Feature Request; I didn't realize there were other tags until you were changing them.

**Comment by evanlinjin** [comment]
@some4 In the case, feature request will be more suitable. Thank you!

**Comment by jdknives** [comment]
@some4 fixed.
