### ISSUE TITLE
Skybian testnet update v0.0.4 failed to deploy to github

### ISSUE THREAD

**Issue by stdevPavelmc** [skycoin/skybian#22]
## Expected Behavior
Skybian must deploy the image to github on build test and completion to make the release.

## Actual Behaviour
The deploy to github step is failing with a credentials error since github 2FA was activated.

## Steps to Reproduce the Problem
Just retrigger the last build and check the travis logs (https://travis-ci.org/skycoin/skybian/jobs/522921354#L764)

## Possible Solution
Update and test the deploy credentials until it works.

**Comment by olemis** [comment]
@stdevPavelmc what logs ?

**Comment by stdevPavelmc** [comment]
> @stdevPavelmc what logs ?

Updated on the main issue text, here for reference: https://travis-ci.org/skycoin/skybian/builds/522921353 in telegram
