### ISSUE TITLE
Hypervisor visor update from UI in Skybian-v0.1.2 fails

### ISSUE THREAD

**Issue by asxtree** [skycoin/skybian#31]
**Describe the bug**
When trying to update the visor that is running on the hypervisor machine from the ui, it fails with error:

`failed to update skychat binary: rename /home/pi/apps/skychat to /tmp/skywire/apps/skychat.old: rename /home/pi/apps/skychat /tmp/skywire/apps/skychat.old: no such file or directory`

**Environment information:**

- Skybian-v0.1.2
- Skywire-v0.2.3

**Steps to Reproduce**

1. Open the hypervisor UI
2. Select the visor that is running on the hypervisor machine and use the Update button
3. The update starts but ends with a failure

**Expected behavior**
The visor should update to the latest release

**Additional context**
See attached photo and log file.

![skywire_update_error_0 2 3_to_0 2 4](https://user-images.githubusercontent.com/34941232/80864762-5d312280-8c8d-11ea-9f93-3277b457a516.png)

[log.txt](https://github.com/SkycoinProject/skybian/files/4567734/log.txt)

**Comment by jdknives** [comment]
@asxtree is this on the regular Skybian or your Skybian for Raspberry Pi?

**Comment by asxtree** [comment]
UPDATE: This issue is encountered only when trying to update the visor that is running on the hypervisor machine.

**Comment by jdknives** [comment]
@asxtree this should be fixed by #380. Once we have the last bits ready for a new release, we will make a new Skybian release and can test whether this has indeed be fixed.
