### ISSUE TITLE
No internet in chroot; apt update, etc. fails during build

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skybian#35]
**Describe the bug**
there is no internet connection inside the chroot when chroot-commands.sh is called

**Environment information:**

- OS: Archlinux
- Platform: x86_64

**Steps to Reproduce**

./build.sh

**Actual behavior**
apt update fails in the chroot.

**Expected behavior**
apt update succeeds in the chroot

**Additional context**

**Possible implementation**
Hints to fix the bug.

**Comment by some4** [comment]
I had this problem before and it was fixed by copying `/etc/resolv.conf` (from host) into chroot.

Iirc it can safely be removed (after doing whatever in chroot) because the network manager should autogenerate one if it's missing on system startup.

Possible fix: 
add a line to `chroot_actions()` in `../skybian/blob/master/build.sh` that copies, then deletes the host `/etc/resolv.conf`

**Comment by 0pcom** [comment]
I've tried copying /etc/resolv.conf to the chroot. Did not work.

That works only if you are chrooting to the same architecture as the host.

I recall with the testnet version of skybian that Pavel worked on that at no time was anything done inside the chroot that required internet connectivity. I have archlinuxARM images, and I've never done that either.

I currntly have commits / edits in the develop branch of Skyfleet/skybian that attempt to make the internet work in the chroot by copying /etc/resolv.conf from host to chroot, and it doesn't work.

```
  # copy host's resolve.conf to root fs
  info "Copying resolve.conf from host to chroot"
  sudo mv ${FS_MNT_POINT}/etc/resolv.conf ${FS_MNT_POINT}/etc/resolv.conf.bak || return 1
  sudo cp "/etc/resolv.conf" "${FS_MNT_POINT}/etc/resolv.conf" || return 1
```
and the resulting error for the build

```
[ INFO ] chroot_actions: Copying chroot script...
[ INFO ] chroot_actions: Copying resolve.conf from host to chroot
[ INFO ] chroot_actions: Seting up chroot jail...
[ INFO ] chroot_actions: Executing chroot script...
[ Info ] Setting default root password to 'skybian'...
Enter new UNIX password: Retype new UNIX password: passwd: password updated successfully
[ Info ] Re-generating the locales info for en_US.UTF-8...
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
[ Info ] Updating your system via APT
Err:1 http://security.debian.org stretch/updates InRelease
  Could not resolve 'security.debian.org'
Err:2 http://httpredir.debian.org/debian stretch InRelease
  Could not resolve 'httpredir.debian.org'
Err:3 http://httpredir.debian.org/debian stretch-updates InRelease
  Could not resolve 'httpredir.debian.org'
Err:4 http://apt.armbian.com stretch InRelease
  Could not resolve 'apt.armbian.com'
Err:5 http://httpredir.debian.org/debian stretch-backports InRelease
  Could not resolve 'httpredir.debian.org'
Reading package lists... Done
W: Failed to fetch http://httpredir.debian.org/debian/dists/stretch/InRelease  Could not resolve 'httpredir.debian.org'
W: Failed to fetch http://httpredir.debian.org/debian/dists/stretch-updates/InRelease  Could not resolve 'httpredir.debian.org'
W: Failed to fetch http://httpredir.debian.org/debian/dists/stretch-backports/InRelease  Could not resolve 'httpredir.debian.org'
W: Failed to fetch http://security.debian.org/dists/stretch/updates/InRelease  Could not resolve 'security.debian.org'
W: Failed to fetch http://apt.armbian.com/dists/stretch/InRelease  Could not resolve 'apt.armbian.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
software-properties-common is already the newest version (0.96.20.2-1).
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: skyfleet.github.io
gpg: no valid OpenPGP data found.
[ ERRO ] main: Failed.
```

The way I work around this with my archlinuxARM images is to use a bootstrapping script that runs once the image is booted.

**Comment by 0pcom** [comment]
possible fix using `systemd-nspawn`:

http://blog.oddbit.com/post/2016-02-07-systemd-nspawn-for-fun-and-well-mostly-f/

**Comment by some4** [comment]
> I've tried copying /etc/resolv.conf to the chroot. Did not work.
> 
> That works only if you are chrooting to the same architecture as the host.
>
Ah, Thank You though for taking the time to try out my suggestion.

> I recall with the testnet version of skybian that Pavel worked on that at no time was anything done inside the chroot that required internet connectivity. I have archlinuxARM images, and I've never done that either.
> 
Like you mentioned: it's tricky making system changes on images built on a different architecture; which is why I'm kinda lurking the repos and seeing where the Dev's take things. They've cleaned up a lot though and have integrated features into Mainnet (e.g. TLS built-in so we don't need to setup encryption and a proxy; keys; node configuration).

> possible fix using `systemd-nspawn`:
>
> http://blog.oddbit.com/post/2016-02-07-systemd-nspawn-for-fun-and-well-mostly-f/
>
Interesting!

**Comment by 0pcom** [comment]
a dirty fix for this issue:

https://github.com/SkycoinProject/skybian/pull/36

**Comment by some4** [comment]
I've successfully built a base image using `make build-skybian-img`.

During the process, I witnessed a system update/upgrade within chroot.

The only roadblock's I hit were: manually installing the `rsync` dependency and running `make` as sudo (for `e2fsck`).

Environment information:

- OS: Debain 10.8
- Platform: x86_64
