### ISSUE TITLE
Updating segmentation fault

### ISSUE THREAD

**Issue by jdknives** [skycoin/skybian#37]
**Describe the bug**
Updating on Skybian to the latest version leads to the following errors (collected with `journalctl`): 

```
May 13 11:17:04 orangepiprime skywire-visor[883]: runtime: function symbol table header: 0x11050 0x0 0x0 0x0 0x0
May 13 11:17:04 orangepiprime skywire-visor[883]: fatal error: invalid function symbol table
May 13 11:17:04 orangepiprime skywire-visor[883]: runtime: panic before malloc heap initialized
May 13 11:17:04 orangepiprime skywire-visor[883]: runtime stack:
```

**Environment information:**

- OS: Skybian

**Steps to Reproduce**

Update to latest behavior of skywire on Skybian. 

**Additional context**
When stopping skywire-visor with `systemctl` and running the binary manually it throws `Segmentation fault`

Running 

```
mkdir ./tmp_folder
cd ./tmp_folder
wget https://github.com/SkycoinProject/skywire-mainnet/releases/download/v0.2.4-test-55015ac/skywire-v0.2.4-test-55015ac-linux-arm64.tar.gz
mkdir skywire-v0.2.4-test-55015ac-linux-arm64
tar xvf ./skywire-v0.2.4-test-55015ac-linux-arm64.tar.gz -C ./skywire-v0.2.4-test-55015ac-linux-arm64
./skywire-v0.2.4-test-55015ac-linux-arm64/skywire-visor
```

works.

**Comment by nkryuchkov** [comment]
@jdknives Could you please reproduce it one more time and do the following?
- Check how much RAM is free
- Check an output of `cat /proc/sys/vm/overcommit_memory`
- If the output is `0`, run `echo 1 > /proc/sys/vm/overcommit_memory` and try to reproduce the issue again
