### ISSUE TITLE
Remote image list not showing up

### ISSUE THREAD

**Issue by Asgaror** [skycoin/skybian#57]
**Describe the bug**
Skyimager is not displaying the available image version from remote:
![image](https://user-images.githubusercontent.com/32180146/98120955-f0524b80-1eae-11eb-8089-b206b6ad9a26.png)

**Environment information:**

- macOS Mojave
- version 10.14.6

**Steps to Reproduce**

2. Run '....'
3. Write data to '....'

**Actual behavior**
In step 2/3 of the Skyimager the option 'From remote server' does not list any entries for the user.

**Expected behavior**
'From remote server' should display several options including the most recent Skybian v0.1.3

**Comment by nkryuchkov** [comment]
@Asgaror Was any connection error like the one above shown before step 2?

<img width="801" alt="image" src="https://user-images.githubusercontent.com/24493220/98250611-b35a8780-1f88-11eb-9bcd-4c788edccd09.png">

**Comment by Asgaror** [comment]
@nkryuchkov yes, that's correct. Sorry for not including this. 

Here's the related conversation on Telegram: https://t.me/skywire/166041
