### ISSUE TITLE
CHANGELOG.md to register changes.

### ISSUE THREAD

**Issue by stdevPavelmc** [skycoin/skybian#6]
## Expected Behavior
The repository must have a CHANGELOG.md to register the changes in time.

## Actual Behavior
It does not have one.

## Possible Solution
Create one and update it every time a relevant change is about to be merged with develop.

**Comment by olemis** [comment]
@stdevPavelmc update every time a relevant change is about to be merged with develop

**Comment by stdevPavelmc** [comment]
Ready with the changes so far, see commit https://github.com/simelo/skybian/commit/5660bc6570b1cad95ae2fe33c482dd43ce23a9c1 ready to be closed on next PR

**Comment by olemis** [comment]
fixed by #9
