### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by jdknives** [skycoin/skybian#65]
**Describe the bug**
I thought it was just an issue on my end (see #64), but apparently Travis had a rate limiting problem in this build as well 

https://travis-ci.com/github/skycoin/skybian/builds/200350631#L7827

We should check what the rate limit is and check if we need to do something about it or if it should be a rare occurence.

**Comment by some4** [comment]
There's a GitHub Doc titled ["Rate limits for GitHub Apps."](https://docs.github.com/en/free-pro-team@latest/developers/apps/rate-limits-for-github-apps#:~:text=GitHub%20Apps%20that%20are%20installed,of%2015%2C000%20requests%20per%20hour.)  It details the limits (per hour) and is based on GitHub account type.

My understanding is that this limit exists between Travis and GitHub.

Line 7827 shows that build failed at "... 12:46:31 ..."; maybe build at the top of the hour?

**Comment by jdknives** [comment]
@some4 correct. The issue I encountered is unlikely to ever pop up for average users. Travis should be fine, we can just restart. Will close this for now.
