### ISSUE TITLE
Document with technical explanation of the process to build the images.

### ISSUE THREAD

**Issue by stdevPavelmc** [skycoin/skybian#7]
## Expected Behavior
Devs and possible contributors needs a simple and clean way to understand how the build script works

## Actual Behavior
There is no place to know that beside peeking on the code.

## Possible Solution
Create a explanatory document with a link on the README.md file (or include it on it)

**Comment by stdevPavelmc** [comment]
Ready to be closed, done in commit https://github.com/simelo/skybian/commit/89174cde664131e2cbcab1b3e4a529046f61a811

**Comment by olemis** [comment]
fixed by #9
