### ISSUE TITLE
Build failing with 404 error on Armbian image archive download

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skybian#8]
**Describe the bug**

This image which is specified in build.conf is no longer available:
https://dl.armbian.com/orangepiprime/archive/Armbian_5.75_Orangepiprime_Debian_stretch_next_4.19.20.7z

**Environment information:**

- OS: Arch Linux
- Platform: Linux 5.5.7-arch1-1 x86_64

**Steps to Reproduce**

```
git clone https://gitub.com/skycoinproject/skybian
cd skybian
./build.sh
```

**Actual behavior**
```
$ ./build.sh
[ Info ] Testing the workspace for needed tools
[ Info ] All tools are installed, going forward.
[ Info ] Creating output folder structure
[ Warning ] Cleaning final images directory
[ Info ] Getting Armbian image, clearing dest dir first.
[ Info ] No cached image, downloading..
[ Info ] Downloading armbian from:
[ Info ] https://dl.armbian.com/orangepiprime/archive/Armbian_5.75_Orangepiprime_Debian_stretch_next_4.19.20.7z
--2020-03-04 12:58:29--  https://dl.armbian.com/orangepiprime/archive/Armbian_5.75_Orangepiprime_Debian_stretch_next_4.19.20.7z
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving dl.armbian.com (dl.armbian.com)... 193.40.103.96, 2001:bb8:4008:20:5054:ff:fea8:96fc
Connecting to dl.armbian.com (dl.armbian.com)|193.40.103.96|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-03-04 12:58:30 ERROR 404: Not Found.
```

**Expected behavior**
build success

**Possible implementation**

* Change build.conf to use this link for the current latest version:
https://dl.armbian.com/orangepiprime/archive/Armbian_20.02.1_Orangepiprime_buster_current_5.4.20.7z

* Change line 200 of build.sh to:
```
    `which sha256sum` -c --status *.sha
```
(or use the full filename of the .sha file)

With these modifications, the build still errors out at `function increase_image_size()` when the rootfs_check is preformed.

this may be because something about the filesystem changed with this armbian release. I can only speculate, but the offending lines appear to be one of these two (330-333 of build.sh)

```
    truncate -s +"${BASE_IMG_ADDED_SPACE}M" "${BASE_IMG}"

    # add free space to the part 1 (sfdisk way)
    echo ", +" | sfdisk -N1 "${BASE_IMG}"
```

**Comment by jdknives** [comment]
Fixed by #11
