### ISSUE TITLE
Refactor Skyimage GUI

### ISSUE THREAD

**Issue by i-hate-nicknames** [skycoin/skybian#90]
skyimager-gui is getting messier with every new feature. The biggest issue is that the code is not properly structured in layers, and UI logic is intertwined with program logic.
[fyne.go](https://github.com/skycoin/skybian/blob/master/pkg/imager/fyne.go) and [fyne_pages.go](https://github.com/skycoin/skybian/blob/master/pkg/imager/fyne_pages.go) are good examples of that.

**Comment by jdknives** [comment]
@i-hate-nicknames thanks. Good point. A few more points from my perspective:

- the UI itself should be simplified:

The intro text is not good. We need to make clear what specifically this tool is supposed to be used for and what to do afterwards. 

The second page which allows build customization should be simplified and likely be split up in three separate sections on their separate page.

The third section should maybe not be shown by default. For most users this is not useful and they should not fiddle around with the values there.

- we need to sign the Mac binary

- we should not archive the windows binary
