### ISSUE TITLE
skywire-visor.json empty after update from 3.0 to 3.6

### ISSUE THREAD

**Issue by tanevanwifferen** [skycoin/skybian#91]
**Describe the bug**
On some nodes, after auto updating the node, skywire-visor.json is empty after the update is done.

**Environment information:**

- OS: Skybian official skyminer
- Platform: Linux 5.10.16-sunxi64 #21.02.2 SMP Sun Feb 14 21:17:31 CET 2021 aarch64

**Steps to Reproduce**

1. Update node
2. Node should work

**Actual behavior**
we have 7 visors, 2 have an empty file 

**Expected behavior**
All 7 visors should come online

**Additional context**
not really

**Possible implementation**
some kind of rotation?

**Comment by jdknives** [comment]
@tanevanwifferen similar to #93 this should be fixed with latest upcoming release. Will release instructions for this in the next few days. Thanks for your ticket. This helps a lot.
