### ISSUE TITLE
Hypervisor doesn't update

### ISSUE THREAD

**Issue by tanevanwifferen** [skycoin/skybian#93]
**Describe the bug**
When using the web UI to update the visors, this all works. However, when updating the hypervisor, it keeps saying it can update from 3.0 to 3.6. It downloads the release, then reboots, then it can be updated again.

**Environment information:**

- OS: Skybian official
- Platform: Linux 5.8.16-sunxi64 #20.08.16 SMP Sat Oct 24 23:52:46 CEST 2020 aarch64

**Steps to Reproduce**

1. Go to the skywire manager ui
2. Run 'update hypervisor'
3. RUn 'update hypervisor' again

**Actual behavior**
It updates twice

**Expected behavior**
The second time it should indicate 'no updates available', 'already on latest version' etc

**Additional context**
Nothing really

**Possible implementation**
No idea

**Comment by jdknives** [comment]
@tanevanwifferen thanks a lot for your issue. We have fixed this and will release instructions how to fix this problem with the upcoming release.
