### ISSUE TITLE
Cleanup documentation

### ISSUE THREAD

**Issue by jdknives** [skycoin/skybian#96]
**Feature description**

The readme seems cluttered with low level information that are likely not helpful for the majority of readers. We should clean that up and just provide necessary info:

- high level idea of the project
- how to build/run
- make release instructions

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Possible implementation**
Preliminary ideas to get this done.
If you have all details in mind then provide a checklist

- [ ] Start with ...
- [ ] When done do ...
- [ ] Finally ...

**Comment by 0pcom** [comment]
the sources and readme have been completely revised since this issue was posted. I assume the current state of the documentation is now adequate
