### ISSUE TITLE
Allow to pass Skyimager and base image version to build

### ISSUE THREAD

**Issue by jdknives** [skycoin/skybian#99]
**Feature description**

It would be nice if we could discern Skywire visors running on Skybian boards from self-built visors. This will help for debugging and may be useful for other purposes. One idea we came up with was to build the binaries when creating the image and use the base version of the image and the Skyimager version as modifiers for the version tag.

There is probably a cleaner way to do something similar as well.

**Comment by mrpalide** [comment]
Additional information about the issue by jdknives:

> The information eventually needs to be displayed in both visor startup log. Currently, we display whether skywire is run as systemd. I would build that out further and not only display whether its systemd service but also whether its Skybian and which version exactly. It should also be displayed in HypervisorUI so should be returned in visor summary I believe.

**Comment by mrpalide** [comment]
Two related PR for skybian and skywire were created.
